spring.application.name=livebflow-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/livebflow
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=America/Sao_Paulo

spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

server.port=8080
